package First.exception;

public class Finalblock {
	public static void main(String[] args) {

		String a = null;

		try {

			System.out.println(a.length());

		} catch (NullPointerException e) {

			e.printStackTrace();
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			

		} finally {

			System.out.println("Finally Block Not Calling Here");
		}
	}


}
